services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI_PROD=${MONGO_URI_PROD}
    restart: unless-stopped

volumes:
  mongodb_data:
